# Generated by Django 3.1.5 on 2021-01-23 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='slug',
        ),
    ]
