# Generated by Django 3.1.4 on 2020-12-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='intro',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
