# Generated by Django 3.1.4 on 2020-12-26 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201225_0004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='testemonial',
            options={'ordering': ['-timestamp']},
        ),
    ]
